#!/bin/bash
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/01%20-%20Key.ogg" -O "Key.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/02%20-%20Door.ogg" -O "Door.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/03%20-%20Subwoofer%20Lullaby.ogg" -O "Subwoofer Lullaby.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/04%20-%20Death.ogg" -O "Death.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/05%20-%20Living%20Mice.ogg" -O "Living Mice.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/06%20-%20Moog%20City.ogg" -O "Moog City.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/07%20-%20Haggstrom.ogg" -O "Haggstrom.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/08%20-%20Minecraft.ogg" -O "Minecraft.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/09%20-%20Oxyg%C3%A8ne.ogg" -O "Oxygene.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/10%20-%20%C3%89quinoxe.ogg" -O "Equinoxe.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/11%20-%20Mice%20on%20Venus.ogg" -O "Mice on venus.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/12%20-%20Dry%20Hands.ogg" -O "Dry Hands.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/13%20-%20Wet%20Hands.ogg" -O "Wet Hands.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/14%20-%20Clark.ogg" -O "Clark.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/15%20-%20Chris.ogg" -O "Chris.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/16%20-%20Thirteen.ogg" -O "Thirteen.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/17%20-%20Excuse.ogg" -O "Excuse.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/18%20-%20Sweden.ogg" -O "Sweden.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/19%20-%20Cat.ogg" -O "Cat.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/20%20-%20Dog.ogg" -O "Dog.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/21%20-%20Danny.ogg" -O "Danny.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/22%20-%20Beginning.ogg" -O "Beginning.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/23%20-%20Droopy%20Likes%20Ricochet.ogg" -O "Droopy Likes Ricochet.ogg"
wget "https://archive.org/download/C418-MinecraftSoundtrackVolumeAlpha/24%20-%20Droopy%20Likes%20Your%20Face.ogg" -O "Droopy Likes Your Face.ogg"
